### ISSUE TITLE
How to infer the home range and movement models for dispersing individuals?

### ISSUE THREAD

**Issue by bniebuhr** [ctmm-initiative/ctmm#23]
Dear ctmm users and developers,

I am working on the home range estimation of a Puma young individual, monitored for 13 months, but I have some trouble fitting ctmm models. 
The animal was released and, some days after, it seems the animal started to disperse long distances for 6 to 7 months, until finally establishing a territory in the last 6 months.

When I take a look at the semivariogram, there is not exactly an estabilization, what suggests me the animal has not established a home range. Take a look here:

![image](https://user-images.githubusercontent.com/8031905/42968229-12b242be-8b79-11e8-9050-cd19deed587a.png)

On the other hand, when I take a look at the time the animal spent around the same location, it is clear that the area used in the second half of the monitoring period is approx. constant, so I would consider that as a home range, at least qualitatively (but this may be quite subjective and arbitrary). Look the figures below. The first one shows the distance from the animal's location to the starting location, that is clearly small in the last half of the monitoring period. 

![distance_begin](https://user-images.githubusercontent.com/8031905/42968395-7df29da8-8b79-11e8-8edd-4187786a3871.png)

The second figure shows the number of relocations within a circle of 2km around each location, which also suggestes that the animal stayed in the same place for a long time, in the last part of the monitoring.

![revisitation](https://user-images.githubusercontent.com/8031905/42968512-da096a90-8b79-11e8-8623-7a861cf3ba23.png)

How should I fit movement models in this case? Should I separate the transient/dispersal data using some kind of criteria? Any hints or opinions?
(because if I fit the models just like that, the confidence intervals and the estimated home range are too large and do not make sense).

Thanks in advance!
Bernardo Niebuhr

**Comment by chfleming** [comment]
Hi Bernardo,

Ideally you would want a model that switched from dispersal behavior to range-resident behavior to estimate the switching time and segment the data accordingly. Unfortunately, we do not yet have these kinds of models in the package, so you will have to segment the data manually.

There are a variety of methods to guide your segmenting of the data, but one that I would consider is the variogram again. If the last 6 months of the data correspond to range-resident behavior, then the variogram of the last 6 months of data should have an asymptote of smaller variance.

As for making sense of the range distribution when the movement behavior is dispersive---this is a dispersal distribution and not a range distribution. It is large because it is predicting what will you see if the puma continues to disperse. The confidence intervals are wide because you did not record many dispersal events. Moreover, if you are using the default maximum-likelihood estimation, the true dispersal range is probably even larger because of the negative bias of maximum likelihood when effective sample sizes are small (and confidence intervals are very large).

https://groups.google.com/forum/#!forum/ctmm-user

Best,
Chris
