### ISSUE TITLE
package website automated workflow

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmm#3]
@chfleming 

Source [this](https://github.com/ctmm-initiative/ctmm/blob/xhdong-pkgsite/inst/pkgsite.R) should generate website automatically.

If the html preview method is preferred, the lines after 16 can be ignored.

**Comment by chfleming** [comment]
I figured out that this bug was the issue:

https://github.com/hadley/pkgdown/issues/207

If I start in a fresh R session and build the vignettes first:

pkgdown::build_articles()
pkgdown::build_news()
pkgdown::build_reference()
pkgdown::build_home()

then everything seems to work (I had to clear my browser cache to see the updates).

**Comment by dracodoc** [comment]
That's good news! So we don't need any hack anymore. Though will the `build_article` take another hour to finish?

**Comment by chfleming** [comment]
It takes a little while, but the plots are rendered at a higher resolution and the navigation menu is built in.

I'm working on a parallelized quasi-Newton optimization routine right now and after that parallelized differentiation (that can handle boundaries), so the fitting will be much faster and that will cut down the vignette compilation time.

**Comment by dracodoc** [comment]
Great. The website is looking pretty good now.
