### ISSUE TITLE
The data import to ctmmweb

### ISSUE THREAD

**Issue by katkagasparova** [ctmm-initiative/ctmm#35]
I have spatial data from GPS satellite units. The position was transmitted every hour with several days-long gaps. Each record include the ID of animal, time, date, longitude, latitude.  I want to analyze them by using ctmm web, as I cannot work with R. I got stacked on data import, I understand they must be in the format of MoveBank, but how I can transfer them into this format when my data are not uploaded in MoveBank. I already tried to add two commas "time GMT" and "date GMT", but still the data are not imported correctly. I would appreciate any help, thanks.

**Comment by chfleming** [comment]
You can import your data into MoveBank without making them publicly available. But, otherwise, you need to have the date and time together in a UTC/GMT "timestamp" column, and the timestamp needs to be in a canonical format. Also, make sure to not edit your data in Microsoft Excel, because it will corrupt your timestamps.

https://ctmm-initiative.github.io/ctmm/reference/as.telemetry.html

https://www.movebank.org/node/2381

https://groups.google.com/forum/#!forum/ctmm-user
